// This file is auto-generated by @hey-api/openapi-ts

export type ApiResponse = {
  /**
   * 响应状态码
   */
  code: number
  /**
   * 响应数据
   */
  data: {
    [key: string]: unknown
  }
  /**
   * 响应消息
   */
  message: string
}

export type UserDto = {
  /**
   * 用户ID
   */
  id: string
  /**
   * 用户名
   */
  username: string
  /**
   * 邮箱
   */
  email: string
  /**
   * 手机号
   */
  phoneNumber: string
  /**
   * 手机号是否已验证
   */
  isPhoneVerified: boolean
  /**
   * 邮箱是否已验证
   */
  isEmailVerified: boolean
  /**
   * 用户头像URL
   */
  avatar?: string
  /**
   * 用户创建时间
   */
  createdAt: Date
  /**
   * 用户更新时间
   */
  updatedAt: Date
  nickname?: string
  roles: Array<string>
  isActive: boolean
}

export type LoginResponseDto = {
  /**
   * 访问令牌
   */
  accessToken: string
  /**
   * 刷新令牌
   */
  refreshToken: string
  /**
   * 用户信息
   */
  user: UserDto
}

export type RegisterResponseDto = {
  /**
   * 访问令牌
   */
  accessToken: string
  /**
   * 刷新令牌
   */
  refreshToken: string
  /**
   * 用户信息
   */
  user: UserDto
}

export type SmsLoginResponseDto = {
  /**
   * 访问令牌
   */
  accessToken: string
  /**
   * 刷新令牌
   */
  refreshToken: string
  /**
   * 用户信息
   */
  user: UserDto
  /**
   * 是否为新用户
   */
  isNewUser: boolean
}

export type RefreshTokenResponseDto = {
  /**
   * 访问令牌
   */
  accessToken: string
  /**
   * 刷新令牌
   */
  refreshToken: string
}

export type LogoutResponseDto = {
  /**
   * 退出登录消息
   */
  message: string
}

export type CreateUserDto = {
  /**
   * 用户名
   */
  username: string
  /**
   * 电子邮件
   */
  email: string
  /**
   * 手机号码
   */
  phoneNumber: string
  /**
   * 密码
   */
  password: string
}

export type LoginUserDto = {
  /**
   * 用户名或手机号
   */
  usernameOrPhone: string
  /**
   * 密码
   */
  password: string
  /**
   * 是否记住登录状态
   */
  rememberMe?: boolean
}

export type SmsLoginDto = {
  /**
   * 手机号码
   */
  phoneNumber: string
  /**
   * 验证码
   */
  code: string
}

export type SolarTerm = {
  /**
   * 主键ID
   */
  id: string
  /**
   * 年份
   */
  pub_year: number
  /**
   * 节气名称
   */
  name: string
  /**
   * 节气公历日期
   */
  pub_date: string
  /**
   * 节气农历日期
   */
  pri_date: string
  /**
   * 节气时间
   */
  pub_time: string
  /**
   * 节气简介
   */
  des: string
  /**
   * 节气由来
   */
  youLai: string
  /**
   * 节气习俗
   */
  xiSu: string
  /**
   * 节气养生建议
   */
  heath: string
}

export type CorsConfigDto = {
  /**
   * 域名
   */
  origin: string
  /**
   * 是否启用
   */
  isActive: boolean
  /**
   * 创建时间
   */
  createdAt: Date
  /**
   * 更新时间
   */
  updatedAt: Date
}

export type AddOriginDto = {
  /**
   * 要添加到CORS白名单的域名
   */
  origin: string
}

export type AddOriginsDto = {
  /**
   * 要批量添加到CORS白名单的域名列表
   */
  origins: Array<string>
}

export type RemoveOriginDto = {
  /**
   * 要从CORS白名单移除的域名
   */
  origin: string
}

export type AuthControllerRegisterData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/auth/register'
}

export type AuthControllerRegisterResponses = {
  /**
   * 注册成功
   */
  201: ApiResponse & {
    data?: RegisterResponseDto
  }
}

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses]

export type AuthControllerLoginData = {
  body: LoginUserDto
  path?: never
  query?: never
  url: '/auth/login'
}

export type AuthControllerLoginResponses = {
  /**
   * 登录成功
   */
  200: ApiResponse & {
    data?: LoginResponseDto
  }
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type AuthControllerSmsLoginData = {
  body: SmsLoginDto
  path?: never
  query?: never
  url: '/auth/sms-login'
}

export type AuthControllerSmsLoginResponses = {
  /**
   * 登录成功
   */
  200: ApiResponse & {
    data?: SmsLoginResponseDto
  }
}

export type AuthControllerSmsLoginResponse =
  AuthControllerSmsLoginResponses[keyof AuthControllerSmsLoginResponses]

export type AuthControllerRefreshTokensData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/refresh'
}

export type AuthControllerRefreshTokensResponses = {
  /**
   * 令牌刷新成功
   */
  200: ApiResponse & {
    data?: RefreshTokenResponseDto
  }
}

export type AuthControllerRefreshTokensResponse =
  AuthControllerRefreshTokensResponses[keyof AuthControllerRefreshTokensResponses]

export type AuthControllerLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/logout'
}

export type AuthControllerLogoutResponses = {
  /**
   * 退出登录成功
   */
  200: ApiResponse & {
    data?: LogoutResponseDto
  }
}

export type AuthControllerLogoutResponse =
  AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses]

export type AuthControllerGetProfileData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/profile'
}

export type AuthControllerGetProfileResponses = {
  /**
   * 获取用户信息成功
   */
  200: ApiResponse & {
    data?: UserDto
  }
}

export type AuthControllerGetProfileResponse =
  AuthControllerGetProfileResponses[keyof AuthControllerGetProfileResponses]

export type SolarTermsControllerGetSolarTermsData = {
  body?: never
  path?: never
  query?: {
    /**
     * 年份，默认为当前年份
     */
    year?: number
  }
  url: '/calendar/solar-terms'
}

export type SolarTermsControllerGetSolarTermsResponses = {
  /**
   * 返回二十四节气数据
   */
  200: Array<SolarTerm>
}

export type SolarTermsControllerGetSolarTermsResponse =
  SolarTermsControllerGetSolarTermsResponses[keyof SolarTermsControllerGetSolarTermsResponses]

export type CorsControllerGetAllowedOriginsData = {
  body?: never
  path?: never
  query?: never
  url: '/system/cors/origins'
}

export type CorsControllerGetAllowedOriginsResponses = {
  /**
   * 获取成功
   */
  200: ApiResponse & {
    data?: Array<CorsConfigDto>
  }
}

export type CorsControllerGetAllowedOriginsResponse =
  CorsControllerGetAllowedOriginsResponses[keyof CorsControllerGetAllowedOriginsResponses]

export type CorsControllerAddOriginsData = {
  body: AddOriginsDto
  path?: never
  query?: never
  url: '/system/cors/origins'
}

export type CorsControllerAddOriginsResponses = {
  /**
   * 批量添加成功
   */
  201: ApiResponse & {
    data?: Array<CorsConfigDto>
  }
}

export type CorsControllerAddOriginsResponse =
  CorsControllerAddOriginsResponses[keyof CorsControllerAddOriginsResponses]

export type CorsControllerRemoveOriginData = {
  body: RemoveOriginDto
  path?: never
  query?: never
  url: '/system/cors/origin'
}

export type CorsControllerRemoveOriginResponses = {
  /**
   * 移除成功
   */
  200: ApiResponse & {
    data?: boolean
  }
}

export type CorsControllerRemoveOriginResponse =
  CorsControllerRemoveOriginResponses[keyof CorsControllerRemoveOriginResponses]

export type CorsControllerAddOriginData = {
  body: AddOriginDto
  path?: never
  query?: never
  url: '/system/cors/origin'
}

export type CorsControllerAddOriginResponses = {
  /**
   * 添加成功
   */
  201: ApiResponse & {
    data?: CorsConfigDto
  }
}

export type CorsControllerAddOriginResponse =
  CorsControllerAddOriginResponses[keyof CorsControllerAddOriginResponses]

export type CorsControllerIsOriginAllowedData = {
  body?: never
  path: {
    origin: string
  }
  query?: never
  url: '/system/cors/origins/check/{origin}'
}

export type CorsControllerIsOriginAllowedResponses = {
  /**
   * 检查成功
   */
  200: ApiResponse & {
    data?: {
      origin?: string
      allowed?: boolean
    }
  }
}

export type CorsControllerIsOriginAllowedResponse =
  CorsControllerIsOriginAllowedResponses[keyof CorsControllerIsOriginAllowedResponses]

export type ClientOptions = {
  baseURL: string
}
